version: '3.8'
services:
  app:
    container_name: api_app
    build:
      context: .
      dockerfile: _docker/prod/Dockerfile
#    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - mysql_db
      - redis
      - meilisearch
    networks:
      - api-network

  web:
    image: nginx:latest
    container_name: api_web
#    build:
#      context: ./
#      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
 #     - ./_docker/prod/nginx/conf.d:/etc/nginx/conf.d
      - ./_docker/prod/nginx/ssl/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./dhparam:/etc/ssl/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    networks:
      - api-network
      - client-network

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    volumes:
      - meilisearch:/data.ms
    ports:
      - 7700:7700
    environment:
      MEILI_MASTER_KEY: "masterKey"
    networks:
      - api-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./:/var/www
    # command: certonly --webroot --webroot-path=/var/www --email kirill.bielousov15151515@gmail.com --agree-tos --no-eff-email --force-renewal -d itsownhouse.ru -d www.itsownhouse.ru -d api.itsownhouse.ru -d www.api.itsownhouse.ru -d meilisearch.itsownhouse.ru -d www.meilisearch.itsownhouse.ru
    depends_on:
      - web
    networks:
      - api-network

  queue-worker:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    container_name: queue
    stop_signal: SIGTERM
    working_dir: /var/www/
    restart: always
    volumes:
      - ./:/var/www
    depends_on:
      - web
    command: php artisan queue:work --tries=3 -n -q
    networks:
      - api-network

  scheduler:
    build:
      context: .
      dockerfile: _docker/scheduler/Dockerfile
    container_name: scheduler
    working_dir: /var/www/
    depends_on:
      - web
    volumes:
      - .:/var/www
    networks:
      - api-network

  redis:
    image: redis:4.0
    container_name: app_redis
    ports:
      - '6379:6379'
    networks:
      - api-network
    volumes:
      - redis:/data
      - ./_docker/redis/sysctl.conf:/etc/sysctl.conf
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"

  mysql_db:
    image: mysql:8.0.25
    # restart: always
    restart: unless-stopped
    tty: true
    container_name: mysql_db
    volumes:
      - dbdata:/var/lib/mysql
#    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - 3306:3306
    networks:
      - api-network

volumes:
  dbdata:
    driver: local
  meilisearch:
    driver: local
  redis:
    driver: local

networks:
  api-network:
    driver: bridge
    name: api-network
  client-network:
    external: true

